### ISSUE TITLE
Live URL is not working

### ISSUE THREAD

**Issue by Starboy-Sharma** [VitorGouveia/Giffy#4]
https://vitorgouveia.github.io/Giffy

![image](https://user-images.githubusercontent.com/31812684/150629808-f7f35eab-a49f-4c33-ae1b-a259198f934d.png)

**Comment by VitorGouveia** [comment]
i know, working on a new nextjs website :)

**Comment by Starboy-Sharma** [comment]
Ohh nice. Good luck 👍
